project:
  title: mb-labs
  type: website
  output-dir: _site

website:
  title: "Mel's Labs"
  favicon: www/favicon.png
  image: www/favicon.png
  twitter-card: true
  site-url: https://mbacou.com
  repo-url: https://github.com/mbacou/mb-labs
  page-navigation: true
  bread-crumbs: false
  description: Playground for consulting and data science projects.

  search:
    location: navbar
    type: overlay
    show-item-context: true

  navbar:
    title: "{{< fa regular compass-drafting >}}   Mel's Labs"
    foreground: dark
    pinned: false
    toggle-position: right

    left:
      - text: Notebooks
        file: index.qmd
      - text: Portfolio
        file: portfolio.qmd
      - text: About
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/mbacou/mb-labs
      - icon: telegram
        href: t.me/mbacou
      - icon: linkedin
        href: https://linkedin.com/in/mbacou
      - icon: youtube
        href: https://www.youtube.com/@mbacou/playlists

  page-footer:
    background: white
    left: |
      &copy; Copyright 2024 &mdash; BACOU, Melanie.
      Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/).
    center:
      - text: About
        href: about.qmd
      - text: License
        href: license.qmd
      - text: RSS
        href: index.xml
    right: "Built with [Quarto^®^](https://quarto.org/)"

bibliography: references.bib

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: left
    link-external-icon: false
    link-external-newwindow: true

    fig-dpi: 220
    fig-format: svg
    fig-width: 7
    fig-height: 4.5

    code-copy: true
    code-overflow: wrap

    tbl-cap-location: top
    fig-cap-location: bottom
    reference-location: margin
    citation-location: document

    theme: www/theme-light.scss
    fontsize: 16px
    title-block-banner: transparent
    grid:
      sidebar-width: 180px
      body-width: 880px
      margin-width: 240px
      gutter-width: 2em
